### ISSUE TITLE
Remove the old index file

### ISSUE THREAD

**Issue by jesseajohnston** [obahizi/obahizi.github.io#1]
Hi Olivier, it looks like the Jekyll site is now there and working. To view the site, you'll need to remove the old `index.html` file. Currently that's the one that you see at the published URL. 

You'll also likely need to update the location variables in your `_config.yml` file, specifically these two:

```
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
```

**Comment by obahizi** [comment]
Hi Prof Jesse,
Thank you so much, I was wondering why I am not seeing the changes.
I will keep working on it.
Thank you for your time.
Olivier

**Comment by jesseajohnston** [comment]
You corrected this @obahizi . I'll close the issue :)
